### ISSUE TITLE
No index.php

### ISSUE THREAD

**Issue by apih** [apih/hello-world#5]
We need an index.php file.

**Comment by AfifMahmood** [comment]
GitHub stores any source code. We can use external third party source to render the files. 

For example
htmlpreview.github.io/?[enter the url to the file here]
ex: htmlpreview.github.io/?https://github.com/AfifMahmood/hello-world/blob/master/README.md

GitHub will not allow server sided code to run.

**Comment by apih** [comment]
But I need a file named as index.php in here...
